redis-ha:
  enabled: false

controller:
  replicas: 1

server:
  autoscaling:
    enabled: false
    # minReplicas: 2

repoServer:
  autoscaling:
    enabled: false
    # minReplicas: 1

applicationSet:
  replicaCount: 1
