apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: main
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - appName: polaris
            namespace: polaris
            version: 5.11.2
          - appName: goldilocks
            namespace: goldilocks
            version: 7.0.2
  template:
    metadata:
      name: "{{appName}}"
      # annotations:
      #   argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: default
      source:
        repoURL: https://charts.fairwinds.com/stable
        targetRevision: "{{version}}"
        chart: "{{appName}}"
        helm:
          # Release name override (defaults to application name)
          # releaseName: "{{appName}}"
          # valueFiles:
          # - "values.yaml"
          # - "../../values/{{name}}/{{appName}}/values.yaml"
      destination:
        # Default base cluster
        name: in-cluster
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
