extraArgs:
- --issuer-ambient-credentials
- --dns01-recursive-nameservers-only

podDnsPolicy: None
podDnsConfig:
  nameservers:
  - "1.1.1.1"
  - "8.8.8.8"

resources:
  requests:
    cpu: 20m
    memory: 200Mi
  limits:
    memory: 325Mi

webhook:
  resources:
    requests:
      cpu: 10m
      memory: 35Mi
    limits:
      memory: 60Mi

cainjector:
  resources:
    requests:
      cpu: 10m
      memory: 175Mi
    limits:
      memory: 250Mi

prometheus:
  enabled: true
